services:
  agents-pgvector:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=agents
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/setup.sql:/docker-entrypoint-inidb.d/setup.sql

volumes:
  pgdata:
